# Generated by Django 3.0.7 on 2020-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_disbursement_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
