# Generated by Django 3.0.7 on 2020-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0003_auto_20201202_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='receipt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='time_served',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
